//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int IDDelivery { get; set; }
        public int IDOrder { get; set; }
        public int IDTransport { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
