//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_2905Entities : DbContext
    {
        public static BD_2905Entities Context;

        public BD_2905Entities()
            : base("name=BD_2905Entities")
        {
        }

        public static BD_2905Entities GetContext()
        {
            if (Context == null)
                Context = new BD_2905Entities();
            return Context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusTransport> StatusTransport { get; set; }
        public virtual DbSet<TOTransport> TOTransport { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
