//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Delivery = new HashSet<Delivery>();
        }
    
        public int IDOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public string NameClient { get; set; }
        public string LastNameClient { get; set; }
        public string Phone { get; set; }
        public int RasstoyanieDelivery { get; set; }
        public int VesGruza { get; set; }
        public System.DateTime SrokDelivery { get; set; }
        public int CountOrder { get; set; }
        public int IDUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual Users Users { get; set; }
    }
}
